server.port=8082

# ==========================
#  DATABASE H2 (local)
# ==========================
spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# ==========================
#  PRODUCT-SERVICE CONFIG
# ==========================
# URL real del microservicio productos
productos.service.url=http://localhost:8081/api

# API-KEY SIMULADA (si después decides implementar validación)
productos.service.api-key=123456

# Tiempo de espera en milisegundos
rest.connect.timeout=2000
rest.read.timeout=3000
